name: unittest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      # CWD -> $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Please don't make me matrix
      - name: Python | Set up 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Archipelago | Setup
        run: |
          wget -qnv -O - https://api.github.com/repos/ArchipelagoMW/Archipelago/releases |
            jq '.[0].tarball_url' |
            xargs wget -nv -O /tmp/Archipelago.tar.gz
          mkdir /tmp/Archipelago
          tar xzf /tmp/Archipelago*.tar.gz -C /tmp/
          mv /tmp/ArchipelagoMW-Archipelago* /tmp/Archipelago
          cd /tmp/Archipelago

      - name: Python | Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-subtests pytest-xdist
            python ModuleUpdate.py --yes --force --append "WebHostLib/requirements.txt"
            python Launcher.py --update_settings
            
      - name: World | Symlink
        run: |
          ln -s $GITHUB_WORKSPACE/manual_traumateam_repod ./worlds/manual_traumateam_repod

      - name: Python | Unittests
        run: |
          pytest -n auto
