name: unittest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  WORLD_NAME: "manual_traumateam_repod"
  WORLD_NAME_PROPER: "Manual_TraumaTeam_RePod"

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      # CWD -> $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Please don't make me matrix
      - name: Python | Set up 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Archipelago | Setup
        working-directory: /tmp
        run: |
          wget -qnv -O - https://api.github.com/repos/ArchipelagoMW/Archipelago/releases |
            jq '.[0].tarball_url' |
            xargs wget -nv -O Archipelago.tar.gz
          tar xzf Archipelago*.tar.gz
          mv ArchipelagoMW-Archipelago* Archipelago

      - name: World | Symlink
        working-directory: /tmp/Archipelago
        run: |
          ln -s $GITHUB_WORKSPACE/$WORLD_NAME ./worlds/$WORLD_NAME

      - name: Python | Install dependencies
        working-directory: /tmp/Archipelago
        run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-subtests pytest-xdist
            python ModuleUpdate.py --yes --force --append "WebHostLib/requirements.txt"
            python Launcher.py --update_settings

      #- name: Python | Unittests
      #  working-directory: /tmp/Archipelago
      #  run: |
      #    pytest test worlds/$WORLD_NAME

      - name: World | Generate Template YAML
        working-directory: /tmp/Archipelago
        run: |
          ls ./worlds
          ls ./worlds/$WORLD_NAME
          python Launcher.py "Generate Template Options"
          ls ./Players/Templates
          
      - name: World | Zip
        working-directory: /tmp/Archipelago/worlds
        run: |
          rm -rf ./$WORLD_NAME/__pycache__/ ./$WORLD_NAME/.idea/
          7z a -tzip $WORLD_NAME.apworld $WORLD_NAME/

      - name: World | Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +"%y.%m.%d")
          TAG=$(git rev-parse --short HEAD)
          gh release create "${DATE}-${TAG}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$TITLE" \
              --target=main \
              --generate-notes \
              --prerelease \
              /tmp/Archipelago/worlds/$WORLD_NAME.apworld \
              /tmp/Archipelago/Players/Templates/$WORLD_NAME_PROPER.yaml
